name: My Python Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Mise à jour vers v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Mise à jour vers v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff

    - name: Run Black
      run: |
        black --check .

    - name: Run Ruff
      run: |
        ruff check .
